version: "2" # version of docker compose

services:
  hardhat-network:
    build: .
    image: hardhat-network-image:latest
    container_name: hardhat-network-container
    hostname: hardhat-network
    restart: "no"
    ports:
      - "8545:8545"
    environment:
      - CHAIN_ID=31337

      # local_net_explorer
      - ETHERNAL_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJlYmFzZVVzZXJJZCI6InFJbzI1WkZhbXRPVk11WENvdzNWdTZRaDROaDIiLCJhcGlLZXkiOiJYMFc5RzNWLUhZRk02N0UtTlNUV0cyQy1NSlBSWFI3XHUwMDAxIiwiaWF0IjoxNzAyOTY2OTY0fQ.dp_l6cMt1c9ge4I1NSPwAXgQ8RtUZ4oFrPbRtVi4KlE
      - ETHERNAL_WORKSPACE=local_net_explorer

      # # remote_net_explorer
      # - ETHERNAL_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJlYmFzZVVzZXJJZCI6Ikp1ajJoMkNRalpVQ0JCYXphYUo2Vk9OY2U4bTIiLCJhcGlLZXkiOiJTSk1DSk5SLU5NSjRGNEstSzhQOUFIUy1ZRDJOR04xXHUwMDAxIiwiaWF0IjoxNzAyOTY5Mzk5fQ.8kuAeWrpM1D_DyAf5tPHIjbXssJz-cM_7SSJrHwxZS8
      # - ETHERNAL_WORKSPACE=remote_net_explorer
