version: "2" # version of docker compose

services:
  hardhat-network:
    build: .
    image: hardhat-network-image:latest
    container_name: hardhat-network-container
    hostname: hardhat-network
    restart: "no"
    ports:
      - "8545:8545"
    environment:
      - ETHERNAL_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJlYmFzZVVzZXJJZCI6ImtxOThlME5BR1dhTlIzUUJTcnYwRjJBbjVZaTEiLCJhcGlLZXkiOiI1WjEzM1NELTcwRDRRUkUtTVdZSkdDWS1CVkFNUEowXHUwMDAxIiwiaWF0IjoxNjkzODM2MDk4fQ.6IJLyKsVPLn9W8IAaQJNpRxR0biQlTkLb02Wz7Jn0M0
      - ETHERNAL_WORKSPACE=local_net_explorer
